# @see https://docs.docker.com/compose/compose-file/compose-file-v3/

x-logging: &default-logging
  driver: json-file
  options:
    max-file: "5"
    max-size: "20m"

services:
  mailhog:
    image: mailhog/mailhog
    container_name: example_app_mailhog
    restart: unless-stopped
    ports:
      - "${MAILHOG_PORT_SMTP}:1025"
      - "${MAILHOG_PORT_UI}:8025"
    logging: *default-logging

  db:
    image: mariadb
    container_name: example_app_db
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    logging: *default-logging

  nginx:
    build: ./docker/nginx/build
    image: nginx
    container_name: example_app_nginx
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "${NGINX_HTTP_PORT}:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/config:/etc/nginx/conf.d:ro
      - ./app:/app
    networks:
      default:
        ipv4_address: ${NGINX_IP}
    logging: *default-logging

  php:
    build: ./docker/php/build
    image: php-8
    container_name: example_app_php
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./docker/php/config/msmtprc:/etc/msmtprc:ro
      - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/my.ini:ro
      - ./docker/php/config/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - composer:/root/.composer/cache
      - ./app:/app
    logging: *default-logging

  rabbitmq:
    image: rabbitmq:management
    build: ./docker/rabbitmq
    container_name: example_app_rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_UI_PORT}:15672"
      - "${RABBITMQ_AMQP_PORT}:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    logging: *default-logging

volumes:
  composer:
  rabbitmq_data:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_NETWORK}
          gateway: ${DOCKER_BRIDGE}
